# Generated by Django 4.1.1 on 2022-12-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(help_text='имя', max_length=100, verbose_name='name')),
                ('Email', models.CharField(help_text='почта', max_length=100, verbose_name='email')),
            ],
        ),
    ]
