# Generated by Django 4.1.1 on 2022-12-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_alter_group_options_alter_group_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='Probability',
            field=models.CharField(blank=True, help_text='С какой вероятностью Вы посетите тренировку?', max_length=100, verbose_name='probability'),
        ),
    ]
