# Generated by Django 4.1.1 on 2022-12-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_group_probability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainers',
            name='age',
        ),
        migrations.AddField(
            model_name='trainers',
            name='experience',
            field=models.IntegerField(blank=True, help_text='Введите опыт работы', null=True, verbose_name='experience'),
        ),
    ]
