# Generated by Django 4.1.1 on 2022-12-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_remove_trainers_age_trainers_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainers',
            name='education',
        ),
        migrations.AddField(
            model_name='trainers',
            name='description',
            field=models.CharField(blank=True, help_text='Введите наименования учреждений,которые вы закончили', max_length=10000, verbose_name='Education'),
        ),
    ]
